using System.Text;

namespace TypeSync.Output.Generators
{
    public abstract class GeneratorBase
    {
        protected string AutogeneratedHeader_CSharpStyle()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// \tThis code was generated by TypeSync.");
            sb.AppendLine("//");
            sb.AppendLine("// \tChanges to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();

            return sb.ToString();
        }

        protected string AutogeneratedHeader_Compact()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// ---------------------------");
            sb.AppendLine("// auto-generated by TypeSync");
            sb.AppendLine("// ---------------------------");
            sb.AppendLine();

            return sb.ToString();
        }
    }
}
